### PR TITLE
Update figures in testing section.

### PR DESCRIPTION
**Pull request by fruffy**

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
What are the vsdx files?

We should merge this, and then if you are almost done i should take a lock on the paper and do a full pass to make sure the text is consistent. Do we have anything else to do?

**Comment by fruffy** [comment]
Those are the Visio source files for the new diagrams I made. Not sure if Visio to you, I can potentially save them in a more open-source friendly format.
My section is pretty much done for now, I'd say.

**Comment by williamtu** [comment]
Do you think the performance evaluation looks ok? If you are curious about more results, I can do some more experiments

**Comment by williamtu** [comment]
Do you think the performance evaluation looks ok? If you are curious about more results, I can do some more experiments

**Pull request merged**
