### PR TITLE
Travis tests.

### PR DESCRIPTION
**Pull request by fruffy**
This branch is intended as a playground to test the travis build script. The goal is to get all tests to run eventually.

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
@fruffy : as you see, this is still failing

**Comment by fruffy** [comment]
Yeah, it is frustrating. Commit 2426409 was passing, which is why I assumed everything is fine. The tests were not skipped either. I am looking into it a bit more.

**Comment by fruffy** [comment]
I am stumped right now. I have not been able to reproduce the conditions under which these tests are failing.
Something in the way the Travis agent is deployed prohibits the creation of namespaces. The Dockerfile works just fine.

**Comment by mbudiu-vmw** [comment]
let's just not run the namespace tests with travis

**Pull request merged**
