### PR TITLE
Migrate to Github Actions

### PR DESCRIPTION
**Pull request by fruffy**

### CODE REVIEW

**Review by mbudiu-vmw — APPROVED** [review]

**Comment by fruffy** [comment]
@mbudiu-vmw Are Github actions enabled for this repository?

**Comment by mbudiu-vmw** [comment]
Had no idea you have to enable them

**Comment by fruffy** [comment]
They should be on by default, but they are not triggered. I will check if there is something off with the script.

**Comment by mbudiu-vmw** [comment]
This being a vmware repository I am not sure what rules apply.

**Comment by fruffy** [comment]
Yes, it looks like Actions are disabled here. So there is not much I can do for now.

**Comment by mbudiu-vmw** [comment]
Is there something I could do?

**Comment by fruffy** [comment]
Are you able/allowed to enable actions for this repository? It can be done in the settings.

**Comment by mbudiu-vmw** [comment]
I can't see a "settings" button for this repository.

**Comment by fruffy** [comment]
Looks like we do not have permission to enable actions for the repository then.

**Comment by fruffy** [comment]
For what it's worth, you can see the passing tests here on my fork:
https://github.com/fruffy/p4c-xdp/runs/5515901442?check_suite_focus=true
All tests pass now, so we can remove the xfails. 

Another thing to note is how fast P4C builds because ccache is properly setup. It only takes a minute. I would like to do this for the main compiler repo but have not gotten it to work because of docker complications.

**Comment by mbudiu-vmw** [comment]
I have checked and github actions are enabled

**Pull request merged**
