### PR TITLE
sudo test

### PR DESCRIPTION
**Pull request by williamtu**

### CODE REVIEW

**Comment by williamtu** [comment]
it turns out that these patches won't help us. 
My end-to-end test need kernel >= 4.13 to support XDP generic driver and the travis-ci is running pretty old kernel. So we can only use travis to test the build process. I'm setting up gitlab internally to see if it helps.

**Comment by mbudiu-vmw** [comment]
Will you be able to run these tests in the cloud?

**Comment by williamtu** [comment]
currently not able to run in the cloud. But I'm thinking about using google cloud to build the more recent kernel and run our end-to-end test.

**Comment by williamtu** [comment]
this one is for adding a bridge with ports + XDP, I think @fruffy already covers this test.

**Pull request closed without merging**
